create table MYUD_Teacher (
	uuid_ VARCHAR(75) null,
	teacherId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	status INTEGER,
	statusByUserId LONG,
	statusByUserName VARCHAR(75) null,
	statusDate DATE null,
	name VARCHAR(75) null,
	biography TEXT null,
	college VARCHAR(75) null,
	rank_ VARCHAR(75) null,
	position VARCHAR(75) null,
	roomNumber VARCHAR(75) null,
	phoneNumber VARCHAR(75) null,
	emailAddress VARCHAR(75) null,
	twitterAddress VARCHAR(75) null,
	googlePlusAddress VARCHAR(75) null,
	linkedinAddress VARCHAR(75) null
);