/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.myportlet.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Teacher service. Represents a row in the &quot;MYUD_Teacher&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.myportlet.model.impl.TeacherModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.myportlet.model.impl.TeacherImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Teacher
 * @generated
 */
@ProviderType
public interface TeacherModel
	extends BaseModel<Teacher>, GroupedModel, ShardedModel, StagedAuditedModel,
			WorkflowedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a teacher model instance should use the {@link Teacher} interface instead.
	 */

	/**
	 * Returns the primary key of this teacher.
	 *
	 * @return the primary key of this teacher
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this teacher.
	 *
	 * @param primaryKey the primary key of this teacher
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this teacher.
	 *
	 * @return the uuid of this teacher
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this teacher.
	 *
	 * @param uuid the uuid of this teacher
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the teacher ID of this teacher.
	 *
	 * @return the teacher ID of this teacher
	 */
	public long getTeacherId();

	/**
	 * Sets the teacher ID of this teacher.
	 *
	 * @param teacherId the teacher ID of this teacher
	 */
	public void setTeacherId(long teacherId);

	/**
	 * Returns the group ID of this teacher.
	 *
	 * @return the group ID of this teacher
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this teacher.
	 *
	 * @param groupId the group ID of this teacher
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this teacher.
	 *
	 * @return the company ID of this teacher
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this teacher.
	 *
	 * @param companyId the company ID of this teacher
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this teacher.
	 *
	 * @return the user ID of this teacher
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this teacher.
	 *
	 * @param userId the user ID of this teacher
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this teacher.
	 *
	 * @return the user uuid of this teacher
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this teacher.
	 *
	 * @param userUuid the user uuid of this teacher
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this teacher.
	 *
	 * @return the user name of this teacher
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this teacher.
	 *
	 * @param userName the user name of this teacher
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this teacher.
	 *
	 * @return the create date of this teacher
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this teacher.
	 *
	 * @param createDate the create date of this teacher
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this teacher.
	 *
	 * @return the modified date of this teacher
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this teacher.
	 *
	 * @param modifiedDate the modified date of this teacher
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the status of this teacher.
	 *
	 * @return the status of this teacher
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this teacher.
	 *
	 * @param status the status of this teacher
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this teacher.
	 *
	 * @return the status by user ID of this teacher
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this teacher.
	 *
	 * @param statusByUserId the status by user ID of this teacher
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this teacher.
	 *
	 * @return the status by user uuid of this teacher
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this teacher.
	 *
	 * @param statusByUserUuid the status by user uuid of this teacher
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this teacher.
	 *
	 * @return the status by user name of this teacher
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this teacher.
	 *
	 * @param statusByUserName the status by user name of this teacher
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this teacher.
	 *
	 * @return the status date of this teacher
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this teacher.
	 *
	 * @param statusDate the status date of this teacher
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns the name of this teacher.
	 *
	 * @return the name of this teacher
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this teacher.
	 *
	 * @param name the name of this teacher
	 */
	public void setName(String name);

	/**
	 * Returns the biography of this teacher.
	 *
	 * @return the biography of this teacher
	 */
	@AutoEscape
	public String getBiography();

	/**
	 * Sets the biography of this teacher.
	 *
	 * @param biography the biography of this teacher
	 */
	public void setBiography(String biography);

	/**
	 * Returns the college of this teacher.
	 *
	 * @return the college of this teacher
	 */
	@AutoEscape
	public String getCollege();

	/**
	 * Sets the college of this teacher.
	 *
	 * @param college the college of this teacher
	 */
	public void setCollege(String college);

	/**
	 * Returns the rank of this teacher.
	 *
	 * @return the rank of this teacher
	 */
	@AutoEscape
	public String getRank();

	/**
	 * Sets the rank of this teacher.
	 *
	 * @param rank the rank of this teacher
	 */
	public void setRank(String rank);

	/**
	 * Returns the position of this teacher.
	 *
	 * @return the position of this teacher
	 */
	@AutoEscape
	public String getPosition();

	/**
	 * Sets the position of this teacher.
	 *
	 * @param position the position of this teacher
	 */
	public void setPosition(String position);

	/**
	 * Returns the room number of this teacher.
	 *
	 * @return the room number of this teacher
	 */
	@AutoEscape
	public String getRoomNumber();

	/**
	 * Sets the room number of this teacher.
	 *
	 * @param roomNumber the room number of this teacher
	 */
	public void setRoomNumber(String roomNumber);

	/**
	 * Returns the phone number of this teacher.
	 *
	 * @return the phone number of this teacher
	 */
	@AutoEscape
	public String getPhoneNumber();

	/**
	 * Sets the phone number of this teacher.
	 *
	 * @param phoneNumber the phone number of this teacher
	 */
	public void setPhoneNumber(String phoneNumber);

	/**
	 * Returns the email address of this teacher.
	 *
	 * @return the email address of this teacher
	 */
	@AutoEscape
	public String getEmailAddress();

	/**
	 * Sets the email address of this teacher.
	 *
	 * @param emailAddress the email address of this teacher
	 */
	public void setEmailAddress(String emailAddress);

	/**
	 * Returns the twitter address of this teacher.
	 *
	 * @return the twitter address of this teacher
	 */
	@AutoEscape
	public String getTwitterAddress();

	/**
	 * Sets the twitter address of this teacher.
	 *
	 * @param twitterAddress the twitter address of this teacher
	 */
	public void setTwitterAddress(String twitterAddress);

	/**
	 * Returns the google plus address of this teacher.
	 *
	 * @return the google plus address of this teacher
	 */
	@AutoEscape
	public String getGooglePlusAddress();

	/**
	 * Sets the google plus address of this teacher.
	 *
	 * @param googlePlusAddress the google plus address of this teacher
	 */
	public void setGooglePlusAddress(String googlePlusAddress);

	/**
	 * Returns the linkedin address of this teacher.
	 *
	 * @return the linkedin address of this teacher
	 */
	@AutoEscape
	public String getLinkedinAddress();

	/**
	 * Sets the linkedin address of this teacher.
	 *
	 * @param linkedinAddress the linkedin address of this teacher
	 */
	public void setLinkedinAddress(String linkedinAddress);

	/**
	 * Returns <code>true</code> if this teacher is approved.
	 *
	 * @return <code>true</code> if this teacher is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this teacher is denied.
	 *
	 * @return <code>true</code> if this teacher is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this teacher is a draft.
	 *
	 * @return <code>true</code> if this teacher is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this teacher is expired.
	 *
	 * @return <code>true</code> if this teacher is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this teacher is inactive.
	 *
	 * @return <code>true</code> if this teacher is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this teacher is incomplete.
	 *
	 * @return <code>true</code> if this teacher is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this teacher is pending.
	 *
	 * @return <code>true</code> if this teacher is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this teacher is scheduled.
	 *
	 * @return <code>true</code> if this teacher is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

}